// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWNjzSs6lxEcVTWGCMpWSow4abXEUW8yo',
    appId: '1:703625303660:web:afbc3e81bf582235282a49',
    messagingSenderId: '703625303660',
    projectId: 'expens-tracker-26810',
    authDomain: 'expens-tracker-26810.firebaseapp.com',
    storageBucket: 'expens-tracker-26810.firebasestorage.app',
    measurementId: 'G-B007ET0YTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFaZ4zMT2-1v8aIGNJ6PEPnL4OPMUYDo',
    appId: '1:703625303660:android:7230bb0a2fb35b4c282a49',
    messagingSenderId: '703625303660',
    projectId: 'expens-tracker-26810',
    storageBucket: 'expens-tracker-26810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8HNzarYN0VhkZP90DwOJR8qk48y9QFo',
    appId: '1:703625303660:ios:7d2664a02080a032282a49',
    messagingSenderId: '703625303660',
    projectId: 'expens-tracker-26810',
    storageBucket: 'expens-tracker-26810.firebasestorage.app',
    iosBundleId: 'com.example.expensTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8HNzarYN0VhkZP90DwOJR8qk48y9QFo',
    appId: '1:703625303660:ios:7d2664a02080a032282a49',
    messagingSenderId: '703625303660',
    projectId: 'expens-tracker-26810',
    storageBucket: 'expens-tracker-26810.firebasestorage.app',
    iosBundleId: 'com.example.expensTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWNjzSs6lxEcVTWGCMpWSow4abXEUW8yo',
    appId: '1:703625303660:web:d4876358d6b63405282a49',
    messagingSenderId: '703625303660',
    projectId: 'expens-tracker-26810',
    authDomain: 'expens-tracker-26810.firebaseapp.com',
    storageBucket: 'expens-tracker-26810.firebasestorage.app',
    measurementId: 'G-Q64G9FT7KH',
  );
}
